# Generated by Django 3.2.9 on 2021-12-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningMounth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mounth_name', models.CharField(max_length=12)),
                ('year', models.CharField(max_length=4)),
                ('first_day', models.IntegerField()),
                ('cleaners', models.TextField()),
            ],
        ),
    ]
